//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string MemberID { get; set; }
        public string TeamID { get; set; }
        public string MemberNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
