//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A50B4C_itchtunticketEntities : DbContext
    {
        public DB_A50B4C_itchtunticketEntities()
            : base("name=DB_A50B4C_itchtunticketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<ClosedTicket> ClosedTickets { get; set; }
        public DbSet<LoginForm> LoginForms { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<Severity> Severities { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<TicketTransition> TicketTransitions { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
