//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTransition
    {
        public string TicketTransitionID { get; set; }
        public string TicketNumber { get; set; }
        public string TeamID { get; set; }
        public string MemberID { get; set; }
        public bool Status { get; set; }
    }
}
