//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string TicketID { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string TeamID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public int Ticket_Severity { get; set; }
        public decimal Ticket_Estimated_Time { get; set; }
        public string TicketNumber { get; set; }
    }
}
